site_name: UniBuddy

repo_name: "2023.1-UniBuddy"
repo_url: "https://github.com/mdsreq-fga-unb/2023.1-UniBuddy"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette: 
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs

nav:
  - Home: index.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg