site_name: UniBuddy

repo_name: "2023.1-UniBuddy"
repo_url: "https://github.com/mdsreq-fga-unb/2023.1-UniBuddy"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette: 
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs

nav:
  - Início: index.md
  - Documentação: 
    - Visão de Produto e Projeto: "visao-produto-projeto.md"
  - Entregas: 
    - Unidade 1:
      - Visão Geral do Produto: "material-processo-er-un1.md"
      - Material do Seminario - Processo Unificado: "material-seminario-processo.md"
    - Unidade 2:
      - Atualização da Visão Geral: "material-processo-er-un2.md"
      - Backlog do Produto: "backlog-mvps-un2.md"
    - Unidade 3:
      - Atualização da Visão Geral: "material-processo-er-un3.md"
      - Atualização do Backlog do Produto: "backlog-mvps-un3.md"
      - MVP1: "mvp1-un3.md"
      - Feedback do Cliente: "feedback-cliente-un3.md"
      - Backlog Estrutura SAFe: "backlog-safe-un3.md"
      - Canvas PBB: "canvas-pbb-un3.md"

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg